name: Check-Python

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/check-python.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/check-python.yml
  schedule:
    - cron: '0 7 * * 2'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  codeql-python:
    permissions:
      actions: read  # for github/codeql-action/init to get workflow details
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/autobuild to send a status report
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          files.pythonhosted.org:443
          github.com:443
          objects.githubusercontent.com:443
          pypi.org:443
          uploads.github.com:443

    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: print env
      run: ./ci/printenv.sh

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@0ba4244466797eb048eb91a6cd43d5c03ca8bd05
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@0ba4244466797eb048eb91a6cd43d5c03ca8bd05
